name: Build PDF
on:
  push:
    branches:
      - master
    paths:
      - 'resume.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: resume.md
          output_dir: resume.pdf
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
